apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname  # Name of the secret
  namespace: webapps  # Namespace where the secret will be created
  annotations:
    kubernetes.io/service-account.name: default  # Links to the service account

---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: mysecretname
  namespace: elk
  annotations:
    kubernetes.io/service-account.name: default

# kubectl get secret mysecretname -n webapps -o jsonpath="{.data.token}" | base64 --decode
# kubectl get secret mysecretname -n elk -o jsonpath="{.data.token}" | base64 --decode