apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: elk
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
        ssl => false # Set to 'true' if using TLS
      }
    }
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"] 
        index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
      }
      stdout { 
        codec => rubydebug
      }
    }
#index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"